In [54]:
from sknetwork.embedding import Spring
from sknetwork.utils import KNNDense, CNNDense
from sknetwork.visualization import svg_graph

In [55]:
import pandas as pd

In [56]:
df = pd.read_csv("data/penguins.csv").dropna()
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.1           18.7              181.0   
1       Adelie  Torgersen            39.5           17.4              186.0   
2       Adelie  Torgersen            40.3           18.0              195.0   
4       Adelie  Torgersen            36.7           19.3              193.0   
5       Adelie  Torgersen            39.3           20.6              190.0   
..         ...        ...             ...            ...                ...   
339  Chinstrap      Dream            55.8           19.8              207.0   
340  Chinstrap      Dream            43.5           18.1              202.0   
341  Chinstrap      Dream            49.6           18.2              193.0   
342  Chinstrap      Dream            50.8           19.0              210.0   
343  Chinstrap      Dream            50.2           18.7              198.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
4         3450.0  female  2007  
5         3650.0    male  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[333 rows x 8 columns]

In [57]:
from algorithms.utils.mixed_distances import huang_distance_matrix

In [58]:
dist = huang_distance_matrix(df)
dist

array([[ 0.        ,  0.698998  ,  1.6875325 , ..., 10.81928036,
        15.41871168, 12.05463227],
       [ 0.698998  ,  0.        ,  0.99611444, ..., 10.28373593,
        14.4706804 , 11.33393799],
       [ 1.6875325 ,  0.99611444,  0.        , ...,  9.8036806 ,
        12.66856339, 10.20696511],
       ...,
       [10.81928036, 10.28373593,  9.8036806 , ...,  0.        ,
         1.85283515,  0.32938366],
       [15.41871168, 14.4706804 , 12.66856339, ...,  1.85283515,
         0.        ,  1.0590008 ],
       [12.05463227, 11.33393799, 10.20696511, ...,  0.32938366,
         1.0590008 ,  0.        ]])

In [59]:
from scipy.sparse.csgraph import minimum_spanning_tree

In [60]:
dist

array([[ 0.        ,  0.698998  ,  1.6875325 , ..., 10.81928036,
        15.41871168, 12.05463227],
       [ 0.698998  ,  0.        ,  0.99611444, ..., 10.28373593,
        14.4706804 , 11.33393799],
       [ 1.6875325 ,  0.99611444,  0.        , ...,  9.8036806 ,
        12.66856339, 10.20696511],
       ...,
       [10.81928036, 10.28373593,  9.8036806 , ...,  0.        ,
         1.85283515,  0.32938366],
       [15.41871168, 14.4706804 , 12.66856339, ...,  1.85283515,
         0.        ,  1.0590008 ],
       [12.05463227, 11.33393799, 10.20696511, ...,  0.32938366,
         1.0590008 ,  0.        ]])

In [61]:
import numpy as np
kernel = np.exp(-dist/2)
kernel

array([[1.00000000e+00, 7.05041228e-01, 4.30087652e-01, ...,
        4.47324948e-03, 4.48610360e-04, 2.41195867e-03],
       [7.05041228e-01, 1.00000000e+00, 6.07710160e-01, ...,
        5.84675798e-03, 7.20662089e-04, 3.45833162e-03],
       [4.30087652e-01, 6.07710160e-01, 1.00000000e+00, ...,
        7.43289173e-03, 1.77441996e-03, 6.07555124e-03],
       ...,
       [4.47324948e-03, 5.84675798e-03, 7.43289173e-03, ...,
        1.00000000e+00, 3.95969703e-01, 8.48155039e-01],
       [4.48610360e-04, 7.20662089e-04, 1.77441996e-03, ...,
        3.95969703e-01, 1.00000000e+00, 5.88899110e-01],
       [2.41195867e-03, 3.45833162e-03, 6.07555124e-03, ...,
        8.48155039e-01, 5.88899110e-01, 1.00000000e+00]])

In [62]:
tree = minimum_spanning_tree(kernel).toarray()

In [63]:
pd.DataFrame(tree).describe()

0      1             2             3      4      5      6    \
count  3.330000e+02  333.0  3.330000e+02  3.330000e+02  333.0  333.0  333.0   
mean   4.871980e-11    0.0  4.255728e-10  3.098669e-11    0.0    0.0    0.0   
std    8.890529e-10    0.0  7.765974e-09  5.654541e-10    0.0    0.0    0.0   
min    0.000000e+00    0.0  0.000000e+00  0.000000e+00    0.0    0.0    0.0   
25%    0.000000e+00    0.0  0.000000e+00  0.000000e+00    0.0    0.0    0.0   
50%    0.000000e+00    0.0  0.000000e+00  0.000000e+00    0.0    0.0    0.0   
75%    0.000000e+00    0.0  0.000000e+00  0.000000e+00    0.0    0.0    0.0   
max    1.622369e-08    0.0  1.417157e-07  1.031857e-08    0.0    0.0    0.0   

         7      8             9    ...    323    324           325  \
count  333.0  333.0  3.330000e+02  ...  333.0  333.0  3.330000e+02   
mean     0.0    0.0  2.745772e-07  ...    0.0    0.0  4.273800e-08   
std      0.0    0.0  3.373615e-06  ...    0.0    0.0  7.798953e-07   
min      0.0    0.0  0.000000e+00  ...    0.0    0.0  0.000000e+00   
25%      0.0    0.0  0.000000e+00  ...    0.0    0.0  0.000000e+00   
50%      0.0    0.0  0.000000e+00  ...    0.0    0.0  0.000000e+00   
75%      0.0    0.0  0.000000e+00  ...    0.0    0.0  0.000000e+00   
max      0.0    0.0  4.355669e-05  ...    0.0    0.0  1.423175e-05   

                326    327           328    329           330    331  \
count  3.330000e+02  333.0  3.330000e+02  333.0  3.330000e+02  333.0   
mean   1.180157e-09    0.0  4.447941e-08    0.0  1.094983e-08    0.0   
std    2.153584e-08    0.0  5.762428e-07    0.0  1.998157e-07    0.0   
min    0.000000e+00    0.0  0.000000e+00    0.0  0.000000e+00    0.0   
25%    0.000000e+00    0.0  0.000000e+00    0.0  0.000000e+00    0.0   
50%    0.000000e+00    0.0  0.000000e+00    0.0  0.000000e+00    0.0   
75%    0.000000e+00    0.0  0.000000e+00    0.0  0.000000e+00    0.0   
max    3.929923e-07    0.0  9.261035e-06    0.0  3.646295e-06    0.0   

                332  
count  3.330000e+02  
mean   2.500975e-08  
std    4.563851e-07  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    8.328247e-06  

[8 rows x 333 columns]

In [65]:
from sklearn.manifold import SpectralEmbedding
SpectralEmbedding(3,affinity="precomputed", gamma=4*len(df.columns)).fit_transform(kernel)

array([[-7.63185672e-03,  7.66973974e-03, -1.54341071e-02],
       [-7.35166647e-03,  6.80763722e-03, -1.40570793e-02],
       [-7.32443683e-03,  7.61809033e-03, -1.24554525e-02],
       [-7.66296302e-03,  5.76106890e-03, -1.51495558e-02],
       [-7.58281592e-03,  9.52190327e-03, -1.31978808e-02],
       [-7.61914811e-03,  6.59033249e-03, -1.58536022e-02],
       [-7.14018073e-03,  9.53329054e-03, -1.00957303e-02],
       [-7.54129553e-03,  8.02147961e-03, -1.47307650e-02],
       [-7.59854849e-03,  9.77399738e-03, -1.31378258e-02],
       [-7.59159686e-03,  8.08648621e-03, -1.32263696e-02],
       [-7.65022078e-03,  4.87637018e-03, -1.61146942e-02],
       [-7.51445565e-03,  7.06958568e-03, -1.34468498e-02],
       [-7.07097179e-03,  1.47123610e-02, -6.05356809e-03],
       [-7.80569311e-03,  3.79650424e-03, -1.75231974e-02],
       [-6.95518540e-03,  2.21257810e-02, -5.27386488e-04],
       [-7.78390697e-03,  6.28327848e-03, -1.79895991e-02],
       [-7.72007846e-03,  6.55597159e-03

In [ ]:
import plotly.express as px